name: Pull Request Workflow

on:
  pull_request:
    types: [opened]

jobs:
  assign-approvers-and-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign approver
        uses: peter-evans/create-pull-request@v3.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          assignee: username_of_approver
      - name: Assign reviewer
        uses: peter-evans/create-pull-request@v3.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          assignee: username_of_reviewer
