name: Auto-Assign Reviewers and Assignees

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Reviewers and Assignees
      uses: actions/bin/assign@v1
      with:
        assignee: Rahi776
        reviewers: Rahi776, octo-org/tools-team

